language: node_js
node_js:
  - '14'

dist: trusty

branches:
  only:
    - master

cache:
  directories:
    - node_modules

install:
  - npm install -g codecov
  - npm install

script:
  - npm test && codecov

notifications:
  email: false
